### ISSUE TITLE
Mise à jour liste des séries après ajout d'une série

### ISSUE THREAD

**Issue by lightningff13** [zarghol/ActuSeries#10]
Actuellement pour voir l'ajout d'une série, on doit se déconnecter puis se reconnecter pour recharger  la liste des séries. On devrait pouvoir voir la mise à jour des séries directement après ajout

**Comment by zarghol** [comment]
je vais regarder ça

**Comment by zarghol** [comment]
réglé

**Comment by lightningff13** [comment]
Tu' l'as pas encore commité?

**Comment by zarghol** [comment]
non j’ai fait d’autres modifs.
bientôt

**Comment by lightningff13** [comment]
ok

Le 6 février 2015 15:51, zarghol notifications@github.com a écrit :

> non j’ai fait d’autres modifs.
> bientôt
> 
> > Le 6 févr. 2015 à 15:50, Charly BRUGERE notifications@github.com a
> > écrit :
> > 
> > Tu' l'as pas encore commité?
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/zarghol/ActuSeries/issues/10#issuecomment-73247345>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zarghol/ActuSeries/issues/10#issuecomment-73247527.

## 

_Brugère Charly_
Elève Ingénieur à Polytech'Lyon
