### ISSUE TITLE
Section de recherche de série

### ISSUE THREAD

**Issue by zarghol** [zarghol/ActuSeries#4]
Activity pour afficher un champ de recherche et le résultat sous forme de liste. 
Implémentation à tous les niveaux (niveaux AccesBetaSerie et niveau BetaSeries => normalement déjà fait, je vais checker)
Possibilité d'ajouter la série au compte.

**Comment by godifreyI** [comment]
Le champs de recherche devrait fonctionner, mais cela n'est pas le cas. 
Voir la gestion de l'event!

**Comment by zarghol** [comment]
bug corrigé, la liste s'affiche correctement !
A voir : afficher une fiche série si on clique dessus, avec un bouton ajouter au compte (je vais écrire les méthodes dans accesbetaseries et betaseries) 
Voir si on peut faire un autre Adapter parce que pour l'instant c'est assez moche ^^

**Comment by zarghol** [comment]
bon, bah je vais faire l'adapter..

**Comment by zarghol** [comment]
fini
